name: sanity

services:
    bingo_db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        ports:
            - ${DB_PORT:-5432}:5432
